export type Challenge = {
  id: number
  word: string
  tip: string
}

export const WORDS: Challenge[] = [
  { id: 1, word: "CSS", tip: "Linguagem de estilos" },
  { id: 2, word: "REACT", tip: "Biblioteca para criar interfaces Web" },
  { id: 3, word: "HTML", tip: "Linguagem de marcação" },
  { id: 4, word: "Javascript", tip: "Uma das linguagens de programação mais utilizadas no mundo" },
  { id: 5, word: "Typescript", tip: "Para adicionar tipagem no Javascript" },
  { id: 6, word: "API", tip: "Interface que permite a comunicação entre diferentes sistemas" },
  { id: 7, word: "Cloud", tip: "Tecnologia que permite o armazenamento e acesso de dados via internet" },
  { id: 8, word: "Git", tip: "Sistema de controle de versões amplamente utilizado por desenvolvedores" },
  { id: 9, word: "Node", tip: "Ambiente de execução para JavaScript no lado do servidor" },
  { id: 10, word: "Python", tip: "Linguagem de programação conhecida por sua simplicidade e legibilidade" },
  { id: 11, word: "Docker", tip: "Plataforma para criação e gerenciamento de containers" },
  { id: 12, word: "Kubernetes", tip: "Sistema de orquestração de containers para automação de aplicações" },
  { id: 13, word: "SQL", tip: "Linguagem usada para gerenciar bancos de dados relacionais" },
  { id: 14, word: "NoSQL", tip: "Tipo de banco de dados que não utiliza o modelo relacional tradicional" },
  { id: 15, word: "DevOps", tip: "Conjunto de práticas que integra desenvolvimento e operações de software" },
  { id: 16, word: "Agile", tip: "Metodologia de desenvolvimento de software focada em entregas rápidas e iterativas" },
  { id: 17, word: "Scrum", tip: "Framework ágil para gerenciamento de projetos complexos" },
  { id: 18, word: "Kanban", tip: "Método visual para gerenciamento de tarefas e fluxos de trabalho" },
  { id: 19, word: "CI/CD", tip: "Práticas de integração e entrega contínuas no desenvolvimento de software" },
  { id: 20, word: "REST", tip: "Estilo de arquitetura para desenvolvimento de serviços web" },
  { id: 21, word: "GraphQL", tip: "Linguagem de consulta para APIs que permite obter apenas os dados necessários" },
  { id: 22, word: "Firebase", tip: "Plataforma do Google para desenvolvimento de aplicativos móveis e web" },
  { id: 23, word: "MongoDB", tip: "Banco de dados NoSQL orientado a documentos" },
  { id: 24, word: "PostgreSQL", tip: "Sistema de gerenciamento de banco de dados relacional de código aberto" },
  { id: 25, word: "Linux", tip: "Sistema operacional de código aberto amplamente utilizado em servidores" },
  { id: 26, word: "Algoritmo", tip: "Sequência de passos para resolver um problema" },
  { id: 27, word: "Backend", tip: "Parte do sistema que lida com a lógica e banco de dados" },
  { id: 28, word: "Frontend", tip: "Parte visual de um sistema com a qual o usuário interage" },
  { id: 29, word: "Fullstack", tip: "Desenvolvedor que atua tanto no frontend quanto no backend" },
  { id: 30, word: "Scrum", tip: "Framework ágil para gerenciamento de projetos" },
  { id: 31, word: "Kanban", tip: "Método visual para gerenciamento de tarefas" },
  { id: 32, word: "CI/CD", tip: "Integração e entrega contínuas no desenvolvimento de software" },
  { id: 33, word: "DevOps", tip: "Cultura que une desenvolvimento e operações" },
  { id: 34, word: "API", tip: "Interface que permite comunicação entre sistemas" },
  { id: 35, word: "REST", tip: "Estilo de arquitetura para desenvolvimento de APIs" },
  { id: 36, word: "GraphQL", tip: "Linguagem de consulta para APIs desenvolvida pelo Facebook" },
  { id: 37, word: "JSON", tip: "Formato leve de troca de dados" },
  { id: 38, word: "XML", tip: "Linguagem de marcação para armazenamento de dados" },
  { id: 39, word: "HTTP", tip: "Protocolo de transferência de hipertexto" },
  { id: 40, word: "HTTPS", tip: "Versão segura do protocolo HTTP" },
  { id: 41, word: "SSL", tip: "Protocolo de segurança para comunicação na internet" },
  { id: 42, word: "TLS", tip: "Sucessor do SSL para segurança na internet" },
  { id: 43, word: "DNS", tip: "Sistema que traduz nomes de domínio em endereços IP" },
  { id: 44, word: "IP", tip: "Endereço que identifica um dispositivo na rede" },
  { id: 45, word: "VPN", tip: "Rede privada virtual para conexão segura" },
  { id: 46, word: "Firewall", tip: "Sistema de segurança que controla o tráfego de rede" },
  { id: 47, word: "Proxy", tip: "Servidor intermediário entre o usuário e a internet" },
  { id: 48, word: "Load Balancer", tip: "Distribui o tráfego entre vários servidores" },
  { id: 49, word: "Cache", tip: "Armazenamento temporário de dados para acesso rápido" },
  { id: 50, word: "Cookie", tip: "Pequeno arquivo armazenado no navegador do usuário" },
  { id: 51, word: "Session", tip: "Período em que um usuário interage com um sistema" },
  { id: 52, word: "Token", tip: "Chave de acesso para autenticação" },
  { id: 53, word: "OAuth", tip: "Protocolo de autorização para acesso a recursos" },
  { id: 54, word: "JWT", tip: "Formato compacto para transmissão de informações seguras" },
  { id: 55, word: "SaaS", tip: "Software como serviço, modelo de distribuição de software" },
  { id: 56, word: "PaaS", tip: "Plataforma como serviço para desenvolvimento de aplicações" },
  { id: 57, word: "IaaS", tip: "Infraestrutura como serviço, fornece recursos computacionais" },
  { id: 58, word: "FaaS", tip: "Função como serviço, modelo de computação serverless" },
  { id: 59, word: "Serverless", tip: "Execução de código sem gerenciamento de servidores" },
  { id: 60, word: "Microservices", tip: "Arquitetura baseada em pequenos serviços independentes" },
  { id: 61, word: "Monolith", tip: "Aplicação construída como uma única unidade" },
  { id: 62, word: "Docker", tip: "Plataforma para criação de containers" },
  { id: 63, word: "Kubernetes", tip: "Sistema de orquestração de containers" },
  { id: 64, word: "CI", tip: "Integração contínua no desenvolvimento de software" },
  { id: 65, word: "CD", tip: "Entrega contínua de software em produção" },
  { id: 66, word: "Git", tip: "Sistema de controle de versões distribuído" },
  { id: 67, word: "GitHub", tip: "Plataforma de hospedagem de código com Git" },
  { id: 68, word: "GitLab", tip: "Plataforma de DevOps baseada em Git" },
  { id: 69, word: "Bitbucket", tip: "Serviço de hospedagem de repositórios Git" },
  { id: 70, word: "Branch", tip: "Ramificação de código em um repositório Git" },
  { id: 71, word: "Merge", tip: "Combinação de branches em Git" },
  { id: 72, word: "Pull Request", tip: "Solicitação de integração de código em Git" },
  { id: 73, word: "Commit", tip: "Registro de alterações em um repositório Git" },
  { id: 74, word: "Rollback", tip: "Reversão de alterações em um sistema" },
  { id: 75, word: "Hotfix", tip: "Correção rápida de um problema crítico" },
  { id: 76, word: "Patch", tip: "Atualização de software para corrigir problemas" },
  { id: 77, word: "Release", tip: "Versão oficial de um software" },
  { id: 78, word: "Beta", tip: "Versão de teste de um software" },
  { id: 79, word: "Alpha", tip: "Versão inicial de um software para testes internos" },
  { id: 80, word: "Stable", tip: "Versão estável de um software pronta para uso" },
  { id: 81, word: "LTS", tip: "Suporte de longo prazo para uma versão de software" },
  { id: 82, word: "CLI", tip: "Interface de linha de comando" },
  { id: 83, word: "GUI", tip: "Alternativo de HUD"},
  { id: 83, word: "GUI", tip: "Interface gráfica do usuário" },
  { id: 84, word: "UX", tip: "Experiência do usuário ao interagir com um produto" },
  { id: 85, word: "UI", tip: "Interface do usuário, o visual de um sistema" },
  { id: 86, word: "Wireframe", tip: "Esboço visual de uma interface" },
  { id: 87, word: "Prototype", tip: "Versão de teste de um produto ou interface" },
  { id: 88, word: "Design System", tip: "Conjunto de padrões de design reutilizáveis" },
  { id: 89, word: "Component", tip: "Elemento reutilizável em frameworks modernos" },
  { id: 90, word: "State", tip: "Estado de um componente em frameworks como React" },
  { id: 91, word: "Props", tip: "Parâmetros passados para componentes React" },
  { id: 92, word: "Hook", tip: "Função especial do React para gerenciar estado e efeitos colaterais" },
  { id: 93, word: "SPA", tip: "Aplicação de página única" },
  { id: 94, word: "SSR", tip: "Renderização do lado do servidor" },
  { id: 95, word: "Next.js", tip: "Framework React com renderização híbrida" },
  { id: 96, word: "Vite", tip: "Ferramenta moderna de build para projetos front-end" },
  { id: 97, word: "Webpack", tip: "Empacotador de módulos JavaScript" },
  { id: 98, word: "Babel", tip: "Compilador JavaScript para versões anteriores" },
  { id: 99, word: "NPM", tip: "Gerenciador de pacotes do Node.js" },
  { id: 100, word: "Yarn", tip: "Gerenciador de pacotes alternativo ao NPM" },
  { id: 101, word: "Package.json", tip: "Arquivo que define as dependências de um projeto Node.js" },
  { id: 102, word: "ESLint", tip: "Ferramenta de análise estática para JavaScript" },
  { id: 103, word: "Prettier", tip: "Formatador de código automático" },
  { id: 104, word: "Lint", tip: "Ferramenta que verifica a qualidade do código" },
  { id: 105, word: "Testing", tip: "Prática de verificar se o software funciona corretamente" },
  { id: 106, word: "Unit Test", tip: "Teste de uma pequena parte do código" },
  { id: 107, word: "Integration Test", tip: "Teste que verifica múltiplas partes juntas" },
  { id: 108, word: "E2E Test", tip: "Teste de ponta a ponta em um sistema completo" },
  { id: 109, word: "Jest", tip: "Framework de testes para JavaScript" },
  { id: 110, word: "Cypress", tip: "Framework de testes end-to-end para web" },
  { id: 111, word: "Mocha", tip: "Framework de testes JavaScript" },
  { id: 112, word: "Chai", tip: "Biblioteca de asserções para testes" },
  { id: 113, word: "Storybook", tip: "Ferramenta para construir e documentar componentes UI" },
  { id: 114, word: "Redux", tip: "Gerenciador de estado para aplicações JavaScript" },
  { id: 115, word: "Context API", tip: "Sistema de gerenciamento de estado do React" },
  { id: 116, word: "Zustand", tip: "Gerenciador de estado leve para React" },
  { id: 117, word: "React Query", tip: "Gerenciador de requisições e cache para React" },
  { id: 118, word: "Axios", tip: "Cliente HTTP baseado em Promises" },
  { id: 119, word: "Fetch", tip: "Função nativa para fazer requisições HTTP" },
  { id: 120, word: "Promise", tip: "Objeto que representa uma operação assíncrona" },
  { id: 121, word: "Async/Await", tip: "Sintaxe para lidar com código assíncrono" },
  { id: 122, word: "Callback", tip: "Função passada como argumento para outra função" },
  { id: 123, word: "Event Loop", tip: "Mecanismo que lida com eventos e callbacks em JavaScript" },
  { id: 124, word: "Closure", tip: "Função que lembra o escopo em que foi criada" },
  { id: 125, word: "Hoisting", tip: "Comportamento de elevação de declarações em JavaScript" },
  { id: 126, word: "Scope", tip: "Contexto onde variáveis e funções são acessíveis" },
  { id: 127, word: "DOM", tip: "Representação estruturada da interface de um documento HTML" },
  { id: 128, word: "BOM", tip: "Modelo de objetos do navegador" },
  { id: 129, word: "WebSocket", tip: "Protocolo para comunicação em tempo real entre cliente e servidor" },
  { id: 130, word: "LocalStorage", tip: "Armazenamento local no navegador" },
  { id: 131, word: "SessionStorage", tip: "Armazenamento temporário no navegador" },
  { id: 132, word: "IndexedDB", tip: "Banco de dados local no navegador" },
  { id: 133, word: "Service Worker", tip: "Script que roda em segundo plano no navegador" },
  { id: 134, word: "PWA", tip: "Aplicações web progressivas que funcionam offline" },
  { id: 135, word: "SEO", tip: "Otimização para mecanismos de busca" },
  { id: 136, word: "SEM", tip: "Marketing em mecanismos de busca" },
  { id: 137, word: "Analytics", tip: "Análise de dados de uso e comportamento" },
  { id: 138, word: "A/B Test", tip: "Teste de duas versões diferentes de um produto" },
  { id: 139, word: "Benchmark", tip: "Teste comparativo de desempenho" },
  { id: 140, word: "Latency", tip: "Tempo de resposta de uma requisição" },
  { id: 141, word: "Throughput", tip: "Quantidade de dados processados em um tempo" },
  { id: 142, word: "Scalability", tip: "Capacidade de crescer sem perder performance" },
  { id: 143, word: "Availability", tip: "Tempo em que um sistema está disponível" },
  { id: 144, word: "Resilience", tip: "Capacidade de recuperação após falhas" },
  { id: 145, word: "Load Test", tip: "Teste de desempenho sob carga pesada" },
  { id: 146, word: "Stress Test", tip: "Teste para ver o limite de um sistema" },
  { id: 147, word: "Security", tip: "Proteção de sistemas e dados contra ameaças" },
  { id: 148, word: "Encryption", tip: "Conversão de dados em formato ilegível" },
  { id: 149, word: "Decryption", tip: "Conversão de dados criptografados para formato original" },
  { id: 150, word: "Malware", tip: "Software malicioso" },
  { id: 151, word: "Phishing", tip: "Técnica de enganar usuários para roubar informações" },
  { id: 152, word: "Ransomware", tip: "Software que bloqueia dados e exige resgate" },
  { id: 153, word: "Pen Test", tip: "Teste de intrusão para encontrar vulnerabilidades" },
  { id: 154, word: "Bug", tip: "Erro no software" },
  { id: 155, word: "Feature", tip: "Nova funcionalidade de um sistema" },
  { id: 156, word: "Refactor", tip: "Reescrever o código sem mudar sua funcionalidade" },
  { id: 157, word: "Legacy", tip: "Código antigo ainda em uso" },
  { id: 158, word: "Tech Debt", tip: "Compromissos técnicos feitos para acelerar entregas" },
  { id: 159, word: "Agile", tip: "Método de desenvolvimento iterativo e incremental" },
  { id: 160, word: "Waterfall", tip: "Modelo de desenvolvimento linear" },
  { id: 161, word: "Sprint", tip: "Período de tempo no Scrum para concluir tarefas" },
  { id: 162, word: "Daily", tip: "Reunião diária do time ágil" },
  { id: 163, word: "Retrospective", tip: "Revisão do que funcionou e o que pode melhorar" },
  { id: 164, word: "Backlog", tip: "Lista priorizada de tarefas a serem feitas" },
  { id: 165, word: "Product Owner", tip: "Responsável por definir prioridades no produto" },
  { id: 166, word: "Scrum Master", tip: "Facilitador do time Scrum" },
  { id: 167, word: "Stakeholder", tip: "Parte interessada em um projeto" },
  { id: 168, word: "MVP", tip: "Produto mínimo viável" },
  { id: 169, word: "Prototype", tip: "Versão inicial de um sistema para testes" },
  { id: 170, word: "Iteration", tip: "Repetição de um ciclo de desenvolvimento" },
  { id: 171, word: "Kanban Board", tip: "Quadro visual para controle de tarefas" },
  { id: 172, word: "Workflow", tip: "Fluxo de trabalho padronizado" },
  { id: 173, word: "Pipeline", tip: "Sequência de etapas de entrega de software" },
  { id: 174, word: "Webhook", tip: "Notificação em tempo real via HTTP" },
  { id: 175, word: "Cron Job", tip: "Tarefa agendada para execução automática" },
  { id: 176, word: "Shell", tip: "Interface de linha de comando para o sistema operacional" },
  { id: 177, word: "Bash", tip: "Linguagem de shell script em sistemas Unix" },
  { id: 178, word: "Zsh", tip: "Shell avançado para terminal Unix" },
  { id: 179, word: "Terminal", tip: "Interface para execução de comandos" },
  { id: 180, word: "SSH", tip: "Protocolo seguro de acesso remoto" },
  { id: 181, word: "FTP", tip: "Protocolo de transferência de arquivos" },
  { id: 182, word: "SFTP", tip: "Versão segura do FTP" },
  { id: 183, word: "JSON Web Token", tip: "Token de autenticação leve e seguro" },
  { id: 184, word: "OAuth2", tip: "Padrão de autorização seguro" },
  { id: 185, word: "Firebase", tip: "Plataforma do Google para desenvolvimento web e mobile" },
  { id: 186, word: "Supabase", tip: "Alternativa open source ao Firebase" },
  { id: 187, word: "Prisma", tip: "ORM moderno para Node.js e TypeScript" },
  { id: 188, word: "ORM", tip: "Mapeamento objeto-relacional" },
  { id: 189, word: "SQL", tip: "Linguagem de consulta a bancos de dados relacionais" },
  { id: 190, word: "NoSQL", tip: "Banco de dados não relacional" },
  { id: 191, word: "Redis", tip: "Banco de dados em memória usado como cache" },
  { id: 192, word: "Elasticsearch", tip: "Motor de busca em tempo real" },
  { id: 193, word: "Kafka", tip: "Plataforma de streaming de eventos" },
  { id: 194, word: "RabbitMQ", tip: "Sistema de mensageria para comunicação entre serviços" },
  { id: 195, word: "Pub/Sub", tip: "Modelo de comunicação assíncrona" },
  { id: 196, word: "Event Driven", tip: "Arquitetura orientada a eventos" },
  { id: 197, word: "CQRS", tip: "Separação de leitura e escrita no banco de dados" },
  { id: 198, word: "DDD", tip: "Design orientado ao domínio" },
  { id: 199, word: "TDD", tip: "Desenvolvimento orientado a testes" },
  { id: 200, word: "Clean Code", tip: "Código claro, legível e de fácil manutenção" }
];
